name: CI

on:
  workflow_dispatch:
  inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
      - info
      - warning
      - debug
    tags:
      description: 'Test scenario tags'
      required: false
      type: boolean
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04	

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: ./script/install_dependencies.sh

    - name: Compile Unit Tests
      run: make test.out

    - name: Run Unit Tests
      run: make check

    - name: Check For Leaks
      run: make check/leaks
